# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a489fd966afe7d2806e55c1d2318da996cc91f60f40caac25298cfb63c69a65d1cecb2003d2217aecc81bfa35515a01049b66b5814d81015258de2675c53d958

test:
  secret_key_base: 350543285cb7c188885a3cc3425138aaa5bec5a0f1cd19a32e08a66f1647b1fa95fdb85553c359612ae0dd8cc4097f5b61ca9bc218b4841152b1827947298cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
